name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: ['8.2', '8.3']
    steps:
      - uses: actions/checkout@v3
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: xdebug
      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: vendor
          key: composer-${{ runner.os }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            composer-${{ runner.os }}-
      - run: composer install --no-interaction --prefer-dist
      - run: vendor/bin/php-cs-fixer fix --dry-run --diff
      - run: vendor/bin/phpstan analyse --no-progress
      - run: mkdir -p build
      - run: vendor/bin/phpunit --coverage-text --coverage-clover build/coverage.xml
        env:
          XDEBUG_MODE: coverage
      - uses: actions/upload-artifact@v4
        with:
          name: php-coverage-${{ matrix.php-version }}
          path: build/coverage.xml
      - uses: actions/setup-node@v3
        if: matrix.php-version == '8.3'
        with:
          node-version: '20'
      - name: Cache npm dependencies
        if: matrix.php-version == '8.3'
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            npm-${{ runner.os }}-
      - run: npm install
        if: matrix.php-version == '8.3'
      - run: npx playwright install --with-deps
        if: matrix.php-version == '8.3'
      - run: npm run test:browser:coverage
        if: matrix.php-version == '8.3'
      - uses: actions/upload-artifact@v4
        if: matrix.php-version == '8.3'
        with:
          name: browser-coverage
          path: build/browser-coverage
